### ISSUE TITLE
Error when saving object with dependant field

### ISSUE THREAD

**Issue by tardinha** [sheadawson/silverstripe-dynamiclists#16]
I have a DynamicListField and DependentDynamicListDropdownField on Member.

After selecting two valid options, I get the "Please select a value within the list provided. {value} is not a valid option" error message.

I've tested this on PHP 5.3 and 5.5 with SS 3.2.5.

Editable fields work fine.

**Comment by Neumes** [comment]
For reference, this is triggering : 

```
[02-Dec-2016 12:24:18] Notice at dynamiclists/code/fields/DependentDynamicListDropdownField.php line 100: Trying to get property of non-object
```

Whereby due to there being tabs in the cms fieldByName wasn't selecting a field and returning null

**Comment by Neumes** [comment]
There is a pending fix for this currently being PR'd

https://github.com/sheadawson/silverstripe-dynamiclists/pull/17

**Comment by tardinha** [comment]
I've tested that, and while i can now save records with the dependant field on them, the field will only save the first value in the list.

Changing the parent works fine, which changes the dependant, but then regardless of what you choose, after save, it reverts to the first item.

**Comment by Neumes** [comment]
The object saves correctly however the display of the value is incorrect when viewing it in the dependent dropdown field. Currently investigating.
